### ISSUE TITLE
unsupported protocol scheme ""

### ISSUE THREAD

**Issue by AdrienLemaire** [binaryplease/base16-universal-manager#30]
Hi @binaryplease , and thanks for working on this manager. I look forward to seeing it become more adopted by base16 users and see an aur package for it.

I tried to install the package, but faced several issues.
Solved:
* needed to mkdir `~/go/src` before running `go install`
* The executable in `~/go/bin/` is base16-universal-manager and not base16-setter

Not solved:
* running base16-universal-manager fails with error "unsupported protocol scheme"

```
$ base16-universal-manager
No templates in list, pulling new one...
panic: Get ?access_token=<mytoken>: unsupported protocol scheme ""

goroutine 1 [running]:
main.check(...)
        /home/dori/go/src/github.com/binaryplease/base16-universal-manager/main.go:150
main.(*Base16ColorschemeList).UpdateSchemes(0xc0000afc00)
        /home/dori/go/src/github.com/binaryplease/base16-universal-manager/colorscheme.go:164 +0x661
main.(*Base16ColorschemeList).Find(0xc0000afc00, 0xc00001a998, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/dori/go/src/github.com/binaryplease/base16-universal-manager/colorscheme.go:198 +0x2a1
main.main()
        /home/dori/go/src/github.com/binaryplease/base16-universal-manager/main.go:87 +0x1b7
```
Couldn't figure out what it's trying to do here.

.config/base16-universal-manager/config.yaml:
```yaml
GithubToken: "<mytoken>"
Colorscheme: "flat.yml"
#DryRun: false  # Print the rendered files to stdout instead of saving them

#https://github.com/binaryplease/base16-universal-manager#applications-which-you-want-to-theme
applications:
  alacritty:
    enabled: true
    files:
      default: "~/.config/alacritty/alacritty.yml"
  vim:
    enabled: true
    files:
      default: "~/.vim/vim_colors"
```

system: Arch linux

What should I do next?
